#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) OwnPulse Contributors
#
# Verify that the nginx.conf proxy upstream hostname matches the Kubernetes
# Service name generated by the waitlist Helm chart. A mismatch here means
# the waitlist form silently breaks in production (502 from nginx).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NGINX_CONF="$REPO_ROOT/nginx.conf"
CHART_PATH="$REPO_ROOT/helm/waitlist"
RELEASE_NAME="waitlist"
NAMESPACE="ownpulse"

# --- 1. Render the Helm chart and extract the Service resource name ----------

rendered=$(helm template "$RELEASE_NAME" "$CHART_PATH" \
  --namespace "$NAMESPACE" \
  --show-only templates/service.yaml)

service_name=$(echo "$rendered" \
  | awk '/^  name:/{print $2; exit}')

if [[ -z "$service_name" ]]; then
  echo "FAIL: could not extract Service name from helm template output" >&2
  exit 1
fi

# --- 2. Extract the waitlist upstream hostname from nginx.conf ---------------

# The upstream is set as:
#   set $waitlist_upstream "http://<hostname>:<port>";
upstream_host=$(sed -n 's/.*set \$waitlist_upstream "http:\/\/\([^:"\/]*\).*/\1/p' "$NGINX_CONF")

if [[ -z "$upstream_host" ]]; then
  echo "FAIL: could not parse waitlist upstream hostname from $NGINX_CONF" >&2
  exit 1
fi

# The nginx.conf uses a fully-qualified cluster DNS name:
#   <service-name>.<namespace>.svc.cluster.local
expected_host="${service_name}.${NAMESPACE}.svc.cluster.local"

# --- 3. Compare --------------------------------------------------------------

if [[ "$upstream_host" == "$expected_host" ]]; then
  echo "OK: nginx upstream matches Helm service name"
  echo "  service name : $service_name"
  echo "  nginx upstream: $upstream_host"
  exit 0
else
  echo "FAIL: nginx upstream does not match Helm service name" >&2
  echo "  expected: $expected_host" >&2
  echo "  found:    $upstream_host" >&2
  echo "" >&2
  echo "  Helm service name: $service_name" >&2
  echo "  (from: helm template $RELEASE_NAME $CHART_PATH)" >&2
  exit 1
fi
