apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ownpulse-waitlist.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ownpulse-waitlist.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ownpulse-waitlist.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ownpulse-waitlist.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command: ['sh', '-c', 'until pg_isready -h {{ include "ownpulse-waitlist.fullname" . }}-postgres -p 5432 -U waitlist; do sleep 2; done']
      containers:
        - name: waitlist
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ownpulse-waitlist.fullname" . }}-postgres
                  key: DATABASE_URL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
